access_token: null
auth_code: null
client_id: Q5QROIR4PL-100
redirect_uri: http://127.0.0.1:8080/algo/index.jsp
response_type: code
secret_key: 89F9TW59G9
state: sample_state
grant_type: authorization_code
