import sys
sys.path.insert(1,r'/home/iob/algotrading')
from core.login import TradeLogin
from core.profile import Profile
from core.order_management import OrderManagement
from strategy.bollinger_breakout import BollingerBreakout
import pandas as pd
trade = TradeLogin()
trade.login()


client_profile = Profile().getProfile()
fund_details =  Profile().getFunds()
orderbook = OrderManagement().fetchPendingOrders()
tradebook = OrderManagement().fetchTradeBook()
positions = OrderManagement().fetchCurrentOverallPositions()
all_positions = OrderManagement().fetchIndividualTradePositions()

symbols = ['NSE:COFORGE-EQ','NSE:KEI-EQ','NSE:ZENSARTECH-EQ','NSE:UNITDSPR-EQ','NSE:APLAPOLLO-EQ','NSE:GPIL-EQ','NSE:APOLLOHOSP-EQ','NSE:BALKRISIND-EQ','NSE:SHYAMMETL-EQ','NSE:INDUSTOWER-EQ','NSE:NBCC-EQ','NSE:TTML-EQ','NSE:WIPRO-EQ','NSE:KOTAKBANK-EQ','NSE:BDL-EQ','NSE:GSPL-EQ','NSE:AADHARHFC-EQ','NSE:PNBHOUSING-EQ','NSE:ICICIPRULI-EQ','NSE:LTTS-EQ','NSE:ZOMATO-EQ','NSE:SCHNEIDER-EQ','NSE:ADANIPOWER-EQ','NSE:INDIANB-EQ','NSE:IRCON-EQ','NSE:HDFCLIFE-EQ','NSE:MPHASIS-EQ','NSE:JMFINANCIL-EQ','NSE:SWANENERGY-EQ','NSE:DEEPAKFERT-EQ','NSE:PEL-EQ','NSE:VEDL-EQ','NSE:MFSL-EQ','NSE:EIDPARRY-EQ','NSE:IDBI-EQ','NSE:BALRAMCHIN-EQ','NSE:UNOMINDA-EQ','NSE:MARUTI-EQ','NSE:WELCORP-EQ','NSE:WELSPUNLIV-EQ','NSE:ICICIGI-EQ','NSE:BSE-EQ','NSE:SUNDARMFIN-EQ','NSE:RKFORGE-EQ','NSE:PERSISTENT-EQ','NSE:FSL-EQ','NSE:TCS-EQ','NSE:ANANDRATHI-EQ','NSE:NAVINFLUOR-EQ','NSE:ZYDUSLIFE-EQ','NSE:SUVENPHAR-EQ','NSE:FLUOROCHEM-EQ','NSE:SRF-EQ','NSE:KIMS-EQ','NSE:GLAND-EQ','NSE:DRREDDY-EQ','NSE:MINDACORP-EQ','NSE:PAYTM-EQ','NSE:OIL-EQ','NSE:BIOCON-EQ','NSE:GVT&D-EQ','NSE:RAINBOW-EQ','NSE:GILLETTE-EQ','NSE:ONGC-EQ','NSE:KIRLOSBROS-EQ','NSE:SYRMA-EQ','NSE:HUDCO-EQ','NSE:LTIM-EQ','NSE:LALPATHLAB-EQ','NSE:JUBLFOOD-EQ','NSE:ANGELONE-EQ','NSE:SBICARD-EQ','NSE:PRAJIND-EQ','NSE:PATANJALI-EQ','NSE:TITAN-EQ','NSE:AEGISLOG-EQ','NSE:SAREGAMA-EQ','NSE:BLS-EQ','NSE:JUSTDIAL-EQ','NSE:IRFC-EQ','NSE:PFC-EQ','NSE:RVNL-EQ','NSE:GICRE-EQ','NSE:CENTURYPLY-EQ','NSE:SAPPHIRE-EQ','NSE:SAMMAANCAP-EQ','NSE:JUBLINGREA-EQ','NSE:RAILTEL-EQ','NSE:REDINGTON-EQ','NSE:GODFRYPHLP-EQ','NSE:BAJFINANCE-EQ','NSE:LEMONTREE-EQ','NSE:FACT-EQ','NSE:CLEAN-EQ','NSE:VGUARD-EQ','NSE:ACE-EQ','NSE:GODIGIT-EQ','NSE:IREDA-EQ','NSE:KAYNES-EQ','NSE:BBTC-EQ','NSE:CRISIL-EQ','NSE:ASTRAZEN-EQ','NSE:KNRCON-EQ','NSE:CONCORDBIO-EQ','NSE:ITI-EQ','NSE:ECLERX-EQ','NSE:FORTIS-EQ','NSE:COCHINSHIP-EQ','NSE:BAJAJHLDNG-EQ','NSE:FIVESTAR-EQ','NSE:HOMEFIRST-EQ','NSE:JSWENERGY-EQ','NSE:KEC-EQ','NSE:TRIVENI-EQ','NSE:CAMPUS-EQ','NSE:LLOYDSME-EQ','NSE:NEWGEN-EQ','NSE:CHALET-EQ','NSE:BLUESTARCO-EQ','NSE:GODREJIND-EQ','NSE:VIJAYA-EQ','NSE:CHEMPLASTS-EQ','NSE:AMBER-EQ','NSE:DATAPATTNS-EQ','NSE:KFINTECH-EQ','NSE:TATAINVEST-EQ','NSE:RAYMOND-EQ','NSE:QUESS-EQ','NSE:PTCIL-EQ','NSE:INTELLECT-EQ','NSE:DEVYANI-EQ','NSE:360ONE-EQ','NSE:MANAPPURAM-EQ','NSE:ASTERDM-EQ','NSE:INDIACEM-EQ','NSE:CAPLIPOINT-EQ','NSE:ANANTRAJ-EQ','NSE:AVANTIFEED-EQ','NSE:JWL-EQ','NSE:TITAGARH-EQ','NSE:TECHNOE-EQ','NSE:JYOTICNC-EQ','NSE:EXIDEIND-EQ','NSE:BASF-EQ','NSE:ARE&M-EQ','NSE:WESTLIFE-EQ','NSE:CRAFTSMAN-EQ','NSE:BHARTIHEXA-EQ']
bb_df = BollingerBreakout().runStrategy('2024-12-18','2025-01-22','5',symbols)